### ISSUE TITLE
Incompatibility with wop 1.15.0

### ISSUE THREAD

**Issue by christophe-david** [fast-aircraft-design/FAST-OAD#356]
**Describe the bug**
Updating wop to version 1.15.0 makes FAST-OAD unusable.

**To Reproduce**
Any command will crash, including `fastoad -v`.

**Error message**
```
Traceback (most recent call last):
  File "/Volumes/MacHD2/Users/tof/PycharmProjects/FAST-OAD_test/.venv/bin/fastoad", line 5, in <module>
    from fastoad.cmd.fast import main
  File "/Volumes/MacHD2/Users/tof/PycharmProjects/FAST-OAD_test/.venv/lib/python3.9/site-packages/fastoad/cmd/fast.py", line 26, in <module>
    from fastoad.cmd import api
  File "/Volumes/MacHD2/Users/tof/PycharmProjects/FAST-OAD_test/.venv/lib/python3.9/site-packages/fastoad/cmd/api.py", line 30, in <module>
    from whatsopt.whatsopt_client import PROD_URL, WhatsOpt
ImportError: cannot import name 'PROD_URL' from 'whatsopt.whatsopt_client' (/Volumes/MacHD2/Users/tof/PycharmProjects/FAST-OAD_test/.venv/lib/python3.9/site-packages/whatsopt/whatsopt_client.py)
```

**Environment**
- Operating System: e.g. macOS 11.4
- Python environment: Python 3.9.5
- Packages: 
  - FAST-OAD 1.0.4
  - wop 1.15.0

**Comment by christophe-david** [comment]
Release 1.15.1 of wop brings back the compatibility. Many thanks @relf !!
