### ISSUE TITLE
Problem inputs cannot have shape_by_conn=True

### ISSUE THREAD

**Issue by christophe-david** [fast-aircraft-design/FAST-OAD#357]
**Describe the bug**
If a problem has an input with variable shape, the problem cannot be run.

**To Reproduce**
With files in this [archive](https://github.com/fast-aircraft-design/FAST-OAD/files/6695352/bug_shape_by_conn.zip) (reproduced below), the command line `fastoad eval conf.yml` crashes.

-   file **`model.py`**
    ```python
    import openmdao.api as om
    import fastoad.api as oad
    
    
    @oad.RegisterOpenMDAOSystem("custom.foo")
    class Foo(om.ExplicitComponent):
        def setup(self):
            self.add_input("foo", shape_by_conn=True)
            self.add_output("bar")
    
        def compute(self, inputs, outputs, discrete_inputs=None, discrete_outputs=None):
            outputs["bar"] = 1.0
    ```

-   file **`conf.yml`**
    ```yaml
    module_folders: modules
    
    input_file: ./problem_inputs.xml
    output_file: ./problem_outputs.xml
    
    model:
      foo:
        id: "custom.foo"
    ```

-   file **`problem_inputs.xml`**
    ```xml
    <FASTOAD_model>
        <foo>[1.0, 2.0]</foo>
    </FASTOAD_model>
    ```

**Expected behavior**
The defined problem has an input with undefined shape, but this shape could be retrieved from the provided XML file.

**Error message**
```
$ fastoad eval conf.yml 
INFO    : Loading bundles from ****/modules
INFO    : Installed bundle modules.model (ID 178 )
INFO    : Installed bundle modules (ID 177 )
Traceback (most recent call last):
  File "****/.venv/bin/fastoad", line 8, in <module>
    sys.exit(main())
  File "****/.venv/lib/python3.9/site-packages/fastoad/cmd/fast.py", line 394, in main
    Main().run()
  File "****/.venv/lib/python3.9/site-packages/fastoad/cmd/fast.py", line 370, in run
    args.func(args)
  File "****/.venv/lib/python3.9/site-packages/fastoad/cmd/fast.py", line 132, in _evaluate
    api.evaluate_problem(args.conf_file, args.force)
  File "****/.venv/lib/python3.9/site-packages/fastoad/cmd/api.py", line 471, in evaluate_problem
    return _run_problem(configuration_file_path, overwrite, "run_model")
  File "****/.venv/lib/python3.9/site-packages/fastoad/cmd/api.py", line 432, in _run_problem
    problem = conf.get_problem(read_inputs=True, auto_scaling=auto_scaling)
  File "****/.venv/lib/python3.9/site-packages/fastoad/io/configuration/configuration.py", line 119, in get_problem
    problem_with_no_inputs.setup()
  File "****/.venv/lib/python3.9/site-packages/openmdao/core/problem.py", line 915, in setup
    model._setup(model_comm, mode, self._metadata)
  File "****/.venv/lib/python3.9/site-packages/openmdao/core/system.py", line 789, in _setup
    self._setup_dynamic_shapes()
  File "****/.venv/lib/python3.9/site-packages/openmdao/core/group.py", line 1716, in _setup_dynamic_shapes
    raise RuntimeError(f"{self.msginfo}: 'shape_by_conn' was set for "
RuntimeError: <model> <class AutoUnitsDefaultGroup>: 'shape_by_conn' was set for unconnected variable 'foo.foo'.
(.venv) TofiMac:bug_shape_by_conn tof$ 

```
**Environment**
- Operating System: macOS 11.4
- Python environment: 3.8.10
- Packages: FAST-OAD 1.0.1, OpenMDAO 3.9.2

**Comment by christophe-david** [comment]
Solved by #416.
